#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Start compositor
picom &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Start polybar, set swedish keyboard and set wallpaper
$HOME/.config/polybar/launch.sh
setxkbmap se &
~/.fehbg &

# Set tapping and natural scrolling
xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1 &
xinput set-prop "Elan Touchpad" "libinput Natural Scrolling Enabled" 1 &

# Enable numlock
numlockx &

# Enable screenshots
flameshot &

